### ISSUE TITLE
Add a version to package.json

### ISSUE THREAD

**Issue by tandrewnichols** [nagoshiashumari/Rpg-Awesome#34]
It would be great if this could be installed via npm. You _could_ just publish it to npm, as the name is not taken, but if you don't want to go that far, npm can install from github urls, but apparently requires `package.json` to include a version number.

**Comment by tandrewnichols** [comment]
Finished via #35

**Comment by idmontie** [comment]
I'll be publishing this some time this week. I'm currently cleaning up the repo and some issues.

Thanks for the PR!
