### ISSUE TITLE
Spelling errors in a few icon tags

### ISSUE THREAD

**Issue by darkenedsky** [nagoshiashumari/Rpg-Awesome#47]
ra-vail => ra-vial
ra-sherif => ra-sheriff
ra-sattelite => ra-satellite
ra-defibrilate => ra-defibrillate
ra-heats-card => ra-hearts-card

May want to add an alias ra-energize for ra-energise (British vs. US spelling)

I would love to help out with some of these tickets. I'd need a quick primer on how to work with the woff files, etc., but if you're willing to invest the time to give me a crash course, I'd be happy to assist!

**Comment by idmontie** [comment]
Some of these are mistakes in the website, some are mistakes in the actual code.

gh-pages:

- [X] ra-vail => ra-vial
- [X] ra-sherif => ra-sheriff
- [X] ra-sattelite => ra-satellite
- [X] ra-defibrilate => ra-defibrillate

Code:

- [X] ra-sherif => ra-sheriff
- [X] ra-sattelite => ra-satellite
- [X] ra-defibrilate => ra-defibrillate

Icons:

- [X] ra-sherif => ra-sheriff
- [X] ra-sattelite => ra-satellite
- [X] ra-defibrilate => ra-defibrillate

**Comment by idmontie** [comment]
<img width="215" alt="screen shot 2018-06-14 at 3 03 30 pm" src="https://user-images.githubusercontent.com/412382/41440635-2155222e-6fe4-11e8-882e-78b46c6650ba.png">

🎉🎉🎉
